project: 
  name: mesa3d
  version: 23.2.0
  summary: Open source implementations of OpenGL, OpenGL ES, Vulkan, OpenCL, and more!
  description: |
    The Mesa project began as an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
    Over the years the project has grown to implement more graphics APIs, including OpenGL ES, OpenCL, OpenMAX, VDPAU, VA-API, XvMC, Vulkan and EGL.
  author: Brian Paul
  email: mesa-dev@lists.freedesktop.org
  license: https://docs.mesa3d.org/license.html
  homepage: https://www.mesa3d.org/

platforms:
  - name: vali
    toolchain: vali/clang-cc=devel
    architectures: [amd64, i386]

environment:
  host:
    packages:
      - build-essential
      - meson
      - python3
  build:
    ingredients:
      - name: vali/sdk-c
        channel: devel
      - name: vali/sdk-cpp
        channel: devel
      - name: vali/libllvm
        channel: devel

recipes:
  - name: libmesa
    path: /
    toolchain: platform
    steps:
    - name: setup
      type: generate
      system: meson
      meson-cross-file: $[[ PROJECT_PATH ]]/chef/vali.meson
      meson-wraps:
        - name: llvm
          ingredient: vali/libllvm
      arguments:
        - -Degl-native-platform=surfaceless
        - -Dgallium-drivers=swrast  
        - -Dgallium-nine=true
        - -Dgallium-d3d10umd=true
        - -Dvulkan-drivers=swrast
        - -Dshader-cache=false
        - -Dshared-glapi=false
        - -Dosmesa=true
      env:
        VALICC: $[[ TOOLCHAIN_PREFIX ]]/usr/local
        VALI_ARCH: $[[ CHEF_TARGET_ARCHITECTURE ]]
        VALI_SDK_PATH: $[[ BUIL_DINGREDIENTS_PREFIX ]]

packs:
- name: mesa
  type: ingredient
